sudo: required
language: generic

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud set config project multi-k8s-314714
  - gcloud set config compute/zone europe-central2-a
  - gcloud set config container clusters get-credentials multi-cluster

 script:
   - docker run -e CI=true mseerah/react-test npm test

 after_success:
   # Log in to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker build -t mseerah/react-test -f ./client/Dockerfile.dev ./client

 deploy:
   provider: script
   script: bash. /deploy.sh
   on:
     branch: master